CREATE TABLE IF NOT EXISTS GOOGLE_OAUTH (
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    REFRESH_TOKEN TEXT NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE IF NOT EXISTS CHAT_LOG (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    QUERY VARCHAR(500) NOT NULL,
    RESPONSE VARCHAR(500) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMAIL) REFERENCES GOOGLE_OAUTH(EMAIL)
);