services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - 8100:8000
    volumes:
      - chromadb_data:/chroma_db

volumes:
  postgres_data:
  chromadb_data: